theme: jekyll-theme-merlot
title: Machine Learning Labs with R
description: This pages gives a variety of sources to learn and Practice Machine Learning. At this time, the focus is on R programming Language; But, we want to extend to 
include python and other programming languages in the near future. 
